Chznged the way of comparing outputs of previous commands

diff --git a/.github/workflows/py.yml b/.github/workflows/py.yml
--- a/.github/workflows/py.yml
+++ b/.github/workflows/py.yml
@@ -22,12 +22,16 @@ jobs:
 
       # Checking format...
       - name: Check code formatting
+        id: black_formatter
         run: |
           black . --check --verbose
+        continue-on-error: true
+
       - name: Check for errors now...
-        shell: bash
+        if: ${{ steps.black_formatter.outputs.exit_code != '0' }}
         run: |
-          "[ $? -eq 0 ] && exit 0 || exit 1"
+          echo "Formatting failed !"
+          exit 1
 
       # Adding logs to the summary
       - name: Logging
diff --git a/.github/workflows/tester.yml b/.github/workflows/tester.yml
--- a/.github/workflows/tester.yml
+++ b/.github/workflows/tester.yml
@@ -44,13 +44,16 @@ jobs:
 
       # Running tests
       - name: Running tests
+        id: unittest_exec
         run: |
           ./build_tests/UnitsTests -c -v
+        continue-on-error: true
 
-      # Checking outputs
-      - name: Checcking the result
+      - name: Check for errors now...
+        if: ${{ steps.unittest_exec.outputs.exit_code != '0' }}
         run: |
-          "[ $? -eq 0 ] && exit 0 || exit 1"
+          echo "Unit tests failed !"
+          exit 1
 
       # Adding logs to the summary
       - name: Logging
